org.hibernate.boot.registry.classloading.spi.ClassLoadingException: Unable to load class [org.springframework.orm.hibernate5.SpringSessionContext] bug was fixed in hibernate.cfg.xml file. were added <property name="current_session_context_class">managed</property>